### ISSUE TITLE
Millis() does not increment during sleep mode, how to get time?

### ISSUE THREAD

**Issue by Syl21** [jerabaul29/ArduinoUseWatchdog#1]
Thanks for your very interesting approach of Arduino sleep and waking-up by the watch-dog timer. I studied your blog six months ago and among the similar topics of other's blogs I find yours very clear and concise. Since then I have implemanted your code in my projects with success. Nevertheless a new issue appeared recently concerning the millis() function, since it is not incremented during the sleep period. My project records a sensor on SD as a function of number of sleeps and tries to avoid RTC to make it smaller and less energy consuming. Please could you tell me if you can find a more trivial solution to obtain the time since the sleep by itself uses a timer, somehow? Thanks a lot for everything.

**Comment by jerabaul29** [comment]
Hej!

Happy to hear that the blog and code are useful.

As you write it, a solution is to write on the SD card both the number of sleeps and the millis() time. You can then estimate the time elapsed a posteriori. I think this is the best solution if you want to avoid a RTC.
